### ISSUE TITLE
Create Batch Service for CSV processing

### ISSUE THREAD

**Issue by SebastianMygind** [audio-engineer/nova-dashboard-back-end#33]
Following this guide: https://spring.io/guides/gs/batch-processing

When recieving a .csv file through a post request, we need to parse the data and then store the collected data in our own database.

The batch service (probably) needs to handle multiple types of csv tables, order being the current focus.

**Comment by audio-engineer** [comment]
It's ok, just keep in mind that you don't need to call stuff like `private static final Logger log = LoggerFactory.getLogger(PersonItemProcessor.class);` or use `schema-all.sql`, etc...
Gotta take our existing code into account

**Comment by audio-engineer** [comment]
Also, make sure to validate the file before starting the bach process, e.g. it should contain the expected header, no. of cols. and no cells should be empty (invalid). You will need some kind of additional service class for that.

Invalid files should be rejected, and the controller should throw an exception that can be displayed on the frontend. You might need a REST exception handler. See e.g. https://www.toptal.com/java/spring-boot-rest-api-error-handling
